/**
 * Gemini CLI agent generator
 * Generates .gemini/commands/deep-verify.toml
 */
const fs = require('fs-extra');
const path = require('node:path');
const { getAgentContent } = require('./agent-base.js');

/**
 * Generate Gemini CLI command file content
 * @param {Object} config - Installation config
 * @returns {string} Gemini command file content (TOML format)
 */
/**
 * Escape quotes for TOML triple-quoted strings
 * @param {string} str - String to escape
 * @returns {string} Escaped string
 */
function escapeToml(str) {
  return str.replaceAll('"""', String.raw`\"\"\"`);
}

function generateGeminiAgent(config) {
  const base = getAgentContent(config);

  const principlesList = base.persona.principles.map((p) => `- ${p}`).join('\n');

  return `# Deep Verifier Agent - Gemini CLI Command
# Generated by deep-verify installer

description = "${escapeToml(base.description)}"

prompt = """
CRITICAL: You are now "${base.alias}", the ${base.title}.

================================================================================
PRE-FLIGHT CHECKLIST - EXECUTE BEFORE ANYTHING ELSE
================================================================================

1. READ CONFIG from: {project-root}/${base.configPath}
   - Note the pattern_domains and default_stakes settings

2. LOAD WORKFLOW from: {project-root}/${base.workflowPath}
   - This is your execution guide - follow it precisely

3. DISPLAY MENU and wait for user command:

   COMMANDS:
   - DV: ${base.commands[0].description}
   - QV: ${base.commands[1].description}

================================================================================
PERSONA
================================================================================

Role: ${base.persona.role}

Identity: ${escapeToml(base.persona.identity)}

Communication Style: ${escapeToml(base.persona.communicationStyle)}

Core Principles:
${principlesList}

================================================================================
CRITICAL RULES
================================================================================

1. NO QUOTE = NO FINDING - Every finding MUST cite exact text from the artifact
2. Mandatory Phase 3 - Always perform adversarial review (except early exit)
3. OUTPUT = REPORT - Your deliverable is a structured verification report
4. DON'T NARRATE - Execute, don't describe what you're about to do
5. LOAD FILES WHEN NEEDED - Read method procedures and data files as needed

================================================================================

Now display the command menu and wait for the user to select DV or QV,
or to provide an artifact for verification.
"""
`;
}

/**
 * Write Gemini agent file to target directory
 * @param {string} targetDir - Target project directory
 * @param {Object} config - Installation config
 * @param {Object} logger - Logger instance
 */
async function writeGeminiAgent(targetDir, config, logger) {
  const content = generateGeminiAgent(config);
  const targetPath = path.join(targetDir, '.gemini', 'commands', 'deep-verify.toml');

  await fs.ensureDir(path.dirname(targetPath));
  await fs.writeFile(targetPath, content);

  logger.log(`   ✓ Created .gemini/commands/deep-verify.toml`);
}

module.exports = {
  generateGeminiAgent,
  writeGeminiAgent,
};
