"""
Deep Process Engine - Output Validator
Version: 0.1
"""

import yaml
from pathlib import Path
from typing import Dict, Any, List

class OutputValidator:
    """Validates if artifacts generated by LLM meet the contract requirements."""

    def __init__(self, project_root: Path):
        self.project_root = project_root

    def validate(self, contract_name: str, file_path: Path) -> Dict[str, Any]:
        """
        Validates a file against a named schema contract.
        
        Args:
            contract_name: Name of the contract (e.g. 'epic', 'story')
            file_path: Path to the generated artifact
            
        Returns:
            Dict with 'valid' (bool) and 'errors' (list[str])
        """
        if not contract_name:
            return {"valid": True, "errors": []} # No contract required

        # 1. Check file existence
        full_path = self.project_root / file_path
        if not full_path.exists():
            return {"valid": False, "errors": [f"File not found: {file_path}"]}

        # 2. Load Content
        try:
            content = full_path.read_text(encoding='utf-8')
            # Assuming artifact is YAML or Markdown with YAML frontmatter
            # For MVP, we try to parse it as YAML
            data = yaml.safe_load(content)
            if not isinstance(data, dict):
                 return {"valid": False, "errors": ["File content is not a valid YAML dictionary"]}
        except Exception as e:
            return {"valid": False, "errors": [f"YAML parsing error: {e}"]}

        # 3. Load Schema (Mocked for now, in real app load from processes/.../schemas/)
        # In future: self.schema_loader.get(contract_name)
        required_fields = self._get_required_fields(contract_name)
        
        errors = []
        for field in required_fields:
            if field not in data:
                errors.append(f"Missing required field: '{field}'")

        return {
            "valid": len(errors) == 0,
            "errors": errors
        }

    def _get_required_fields(self, contract_name: str) -> List[str]:
        """Returns required fields for known contracts. (Hardcoded for MVP)"""
        schemas = {
            "epic": ["id", "title", "description", "status"],
            "story": ["id", "epic_id", "title", "acceptance_criteria", "status"],
            "idea": ["problem_statement", "target_user", "success_criteria"]
        }
        return schemas.get(contract_name, [])
